Serilog:
  Options:
    PostgreSql:
      Enabled: true
    EnableHttpLogging: false
  Using:
    - Serilog.Sinks.Console
    - Serilog.Sinks.File
    - Serilog.Sinks.PostgreSQL
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Information
      System: Information
  WriteTo:
    - Name: Console
    - Name: File
      Args:
        path: "./logs/log-development-.txt"
        rollingInterval: Day
        rollOnFileSizeLimit: true
        formatter: "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact"
  Enrich:
    - FromLogContext
    - WithMachineName
    - WithProcessId
    - WithThreadId
  Properties:
    Application: "Your ASP.NET Core App"

Database:
  HOST: 213.199.46.212
  USERNAME: postgres
  PASSWORD: 123456789
  PORT: 5432
  NAME: budget
    